name: shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "This is a string being executed for workflow"
      - name: multiline script
        run: |
          node -v
          npm -v
          sleep 1000